name: "AWS Security Group IP Modifier"
description: "Add or remove the GitHub Action runner's IP to/from a Security Group using AWS credentials dynamically by account ID"
author: "Your Name"
inputs:
  account-id:
    description: "AWS Account ID to use (mapped to credentials in .env)"
    required: true
  aws-region:
    description: "AWS Region"
    required: true
  security-group-id:
    description: "Security Group ID"
    required: true
  port:
    description: "Port to allow or remove"
    required: true
  protocol:
    description: "Protocol to use (default: tcp)"
    required: false
    default: "tcp"
  to-port:
    description: "Optional: To port"
    required: false
  action:
    description: "Whether to add or remove IP (add/remove)"
    required: true
  description:
    description: "Description for the rule"
    required: false
    default: "GitHub runner IP"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
  - --security-group-id
  - ${{ inputs.security-group-id }}
  - --port
  - ${{ inputs.port }}
  - --protocol
  - ${{ inputs.protocol }}
  - --description
  - ${{ inputs.description }}
  - --region
  - ${{ inputs.aws-region }}
  - --action
  - ${{ inputs.action }}
  - --account-id
  - ${{ inputs.account-id }}
