name: 'AWS Security Group IP Modifier'
description: 'Add or remove an IP to/from an AWS security group'

inputs:
  aws-access-key-id:
    required: true
    description: 'AWS Access Key ID'
  aws-secret-access-key:
    required: true
    description: 'AWS Secret Access Key'
  aws-region:
    required: true
    description: 'AWS Region (e.g., us-east-1)'
  security-group-id:
    required: true
    description: 'AWS Security Group ID'
  port:
    required: true
    description: 'Port to open (e.g., 22)'
  protocol:
    required: false
    default: 'tcp'
    description: 'Protocol for the rule (default: tcp)'
  description:
    required: false
    default: 'GitHub Action IP'
    description: 'Description for the rule'
  to-port:
    required: false
    description: 'ToPort if different from FromPort'
  action:
    required: true
    description: 'Action to perform: add or remove IP'
  account-id:
    required: true
    description: 'Account number like 106 or 5646'

runs:
  using: 'composite'
  steps:
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.12'

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install boto3 requests
    shell: bash

  - name: Set AWS credentials as environment variables
    env:
      AWS_ACCESS_KEY_ID_106: ${{ secrets.AWS_ACCESS_KEY_ID_106 }}
      AWS_SECRET_ACCESS_KEY_106: ${{ secrets.AWS_SECRET_ACCESS_KEY_106 }}
      AWS_ACCESS_KEY_ID_5646: ${{ secrets.AWS_ACCESS_KEY_ID_5646 }}
      AWS_SECRET_ACCESS_KEY_5646: ${{ secrets.AWS_SECRET_ACCESS_KEY_5646 }}
      AWS_ACCESS_KEY_ID_900: ${{ secrets.AWS_ACCESS_KEY_ID_900 }}
      AWS_SECRET_ACCESS_KEY_900: ${{ secrets.AWS_SECRET_ACCESS_KEY_900 }}
      AWS_ACCESS_KEY_ID_365: ${{ secrets.AWS_ACCESS_KEY_ID_365 }}
      AWS_SECRET_ACCESS_KEY_365: ${{ secrets.AWS_SECRET_ACCESS_KEY_365 }}
    run: |
      python3 "${{ github.action_path }}"/main.py \
            --security-group-id ${{ github.event.inputs.security-group-id }} \
            --port ${{ github.event.inputs.port }} \
            --protocol ${{ github.event.inputs.protocol }} \
            --description ${{ github.event.inputs.description }} \
            --region ${{ github.event.inputs.region }} \
            --action ${{ github.event.inputs.action }} \
            --account-id ${{ github.event.inputs.account-id }}
    shell: bash
