name: AWS Security Group IP Modifier

description: 'Add and remove IP to/from AWS security group'

inputs:
  account-id:
    required: true
    description: 'AWS Account ID'
  aws-region:
    required: true
    description: 'AWS Region'
  security-group-id:
    required: true
    description: 'Security Group ID'
  port:
    required: true
    description: 'Port to allow'
  action:
    required: true
    description: "Action to perform: 'add' or 'remove' IP"

runs:
  using: 'composite'
  steps:
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.12'
  - name: Run Python script to add/remove IP
    run: |
      python3 "${{ github.action_path }}/main.py" \
        --account-id ${{ inputs.account-id }} \
        --security-group-id ${{ inputs.security-group-id }} \
        --port ${{ inputs.port }} \
        --action ${{ inputs.action }} \
        --region ${{ inputs.aws-region }}
    shell: bash
