name: AWS Security Group IP Modifier

description: 'Add or remove IP to/from an AWS security group based on the runner IP and account ID'

inputs:
  account-id:
    required: true
    description: 'AWS Account ID (used to fetch corresponding credentials from secrets)'
  aws-region:
    required: true
    description: 'AWS Region (e.g., us-east-1)'
  security-group-id:
    required: true
    description: 'AWS Security Group ID to modify'
  port:
    required: true
    description: 'Port to allow or revoke access (e.g., 22)'
  action:
    required: true
    description: "Action to perform: 'add' or 'remove'"

runs:
  using: 'composite'
  steps:
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.12'

  - name: Install Python dependencies
    run: |
      python3 -m pip install --upgrade pip
      pip install boto3 requests
    shell: bash

  - name: Run Python script to add/remove IP
    run: |
      python3 "${{ github.action_path }}/main.py" \
        --account-id "${{ inputs.account-id }}" \
        --security-group-id "${{ inputs.security-group-id }}" \
        --port "${{ inputs.port }}" \
        --action "${{ inputs.action }}" \
        --aws-region "${{ inputs.aws-region }}"
    shell: bash
